[package]
name = "LiveDebR"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "debr"
path = "debr/main.rs"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = { version = "1.0"}