name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Read release.md and replace {$tag} with actual tag
      id: read_release
      shell: bash
      run: |
        # Read release.md
        r=$(cat release.md)
        # Replace {$tag} with the actual tag from the workflow
        r="${r//\{\$tag\}/${{ github.ref_name }}}"
        r="${r//'%'/'%25'}"  # Escape %
        r="${r//$'\n'/'%0A'}"  # Escape newlines
        r="${r//$'\r'/'%0D'}"  # Escape carriage returns
        echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT  # Set environment variable for release body
    - name: Run build_builder.sh
      run: |
        chmod +x build_builder.sh
        ./build_builder.sh  # Run the build script
    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/builder.tar.gz
        asset_name: builder_linux_amd64.tar.gz
        tag: ${{ github.ref_name }}
        overwrite: true
        prerelease: true
        make_latest: false
        body: ${{ steps.read_release.outputs.RELEASE_BODY }}  # Use the content of release.md as the body
