name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    container:
      image: debian:latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies (make, curl, Rust, build-essential, ntpdate)
      run: |
        apt update
        apt install -y make curl build-essential ntpdate

        # Sync the system clock to avoid clock skew
        ntpdate -u pool.ntp.org

        # Install Rust via rustup (non-interactive with -y)
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    - name: Read release.md and replace {$tag} with actual tag
      id: read_release
      shell: bash
      run: |
        r=$(cat release.md)
        # Replace {$tag} with the actual tag from the workflow
        r="${r//\{\$tag\}/${{ github.ref_name }}}"
        r="${r//'%'/'%25'}"  # Escape %
        r="${r//$'\n'/'%0A'}"  # Escape newlines
        r="${r//$'\r'/'%0D'}"  # Escape carriage returns
        echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT

    - name: Build builder
      run: |
        # Use . to source the cargo environment
        . "$HOME/.cargo/env"  # This works in both sh and bash
        make builder

    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/builder.tar.gz
        asset_name: builder_deb_linux_amd64.tar.gz  # Update the asset name to include "deb"
        tag: ${{ github.ref_name }}
        overwrite: true
        prerelease: true
        make_latest: false
        body: ${{ steps.read_release.outputs.RELEASE_BODY }}  # Use the content of release.md as the body
