name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    container:
      image: debian:latest
      options: --privileged

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: make curl build-essential libssl-dev pkg-config procps wget
        version: 1.0

    - name: Install remaining dependencies
      run: |
        wget https://mega.nz/linux/repo/Debian_12/amd64/megacmd-Debian_12_amd64.deb 
        apt install -y "$PWD/megacmd-Debian_12_amd64.deb"
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    - name: Build builder
      run: |
        . "$HOME/.cargo/env"  # add freshly installed cargo to $path
        make builder
        
    - name: Read release.md and append debr_usage.md
      id: read_release
      shell: bash
      run: |
        # Escape function
        escape_content() {
          local content="$1"
          content="${content//'%'/'%25'}"  # Escape %
          content="${content//$'\n'/'%0A'}"  # Escape newlines
          content="${content//$'\r'/'%0D'}"  # Escape carriage returns
          echo "$content"
        }

        # Process release.md
        release_content=$(cat release.md)
        release_content="${release_content//\{\$tag\}/${{ github.ref_name }}}"
        escaped_release=$(escape_content "$release_content")

        # Process debr_usage.md
        usage_content=$(cat debr_usage.md)
        escaped_usage=$(escape_content "$usage_content")

        # Combine results
        final_release="${escaped_release}%0A${escaped_usage}"
        echo "RELEASE_BODY=$final_release" >> $GITHUB_OUTPUT

    - name: Upload builder
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/builder.tar.gz
        asset_name: builder_linux_amd64_deb.tar.gz 
        tag: ${{ github.ref_name }}
        overwrite: true
        prerelease: true
        make_latest: true
        body: ${{ steps.read_release.outputs.RELEASE_BODY }}
    - name: Upload keyringer
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/builder/assets/keyringer
        asset_name: keyringer
        tag: ${{ github.ref_name }}
        overwrite: true
        prerelease: true
        make_latest: true
        body: ${{ steps.read_release.outputs.RELEASE_BODY }}
    - name: Build iso
      run: |
        make build
        mkdir release
        gzip -c out/live/live-image-amd64.hybrid.iso > "release/live-image-amd64-${{ github.ref_name }}.hybrid.iso.gz"
    - name: Mega upload
      run: |
          mega-login "$USERNAME" "$PASSWORD"
          mega-put "release/live-image-amd64-${{ github.ref_name }}.hybrid.iso.gz" /liveDebR/
      env:
          USERNAME: ${{ secrets.MEGA_USERNAME }}
          PASSWORD: ${{ secrets.MEGA_PASSWORD }}
