name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Read release.md
      id: read_release
      shell: bash
      run: |
        # Read and replace tag placeholder in release.md
        tag=${{ github.ref_name }}
        r=$(cat release.md)
        r="${r//\{\$tag\}/$tag}"  # Replace {$tag} with actual tag
        r="${r//'%'/'%25'}"
        r="${r//$'\n'/'%0A'}"
        r="${r//$'\r'/'%0D'}"
        echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT
    - name: Build binary
      run: cargo build --release
    - name: Create tar.gz
      run: |
        mkdir -p builder
        cp target/release/LiveDebR builder/
        tar -czvf builder.tar.gz builder
    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: builder.tar.gz
        asset_name: builder_linux_amd64.tar.gz
        tag: ${{ github.ref_name }}
        overwrite: true
        prerelease: true
        make_latest: false
        body: ${{ steps.read_release.outputs.RELEASE_BODY }}
