name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    container:
      image: debian:latest
      options: --privileged

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt update
        apt install -y make
        make deps

    - name: Build builder
      run: |
        . "$HOME/.cargo/env"  # add freshly installed cargo to $path
        make builder
        
    - name: Read release.md and append debr_usage.md
      id: read_release
      shell: bash
      run: |
        # Escape function
        escape_content() {
          local content="$1"
          content="${content//'%'/'%25'}"  # Escape %
          content="${content//$'\n'/'%0A'}"  # Escape newlines
          content="${content//$'\r'/'%0D'}"  # Escape carriage returns
          echo "$content"
        }

        # Process release.md
        release_content=$(cat release.md)
        release_content="${release_content//\{\$tag\}/${{ github.ref_name }}}"
        escaped_release=$(escape_content "$release_content")

        # Process debr_usage.md
        usage_content=$(cat debr_usage.md)
        escaped_usage=$(escape_content "$usage_content")

        # Combine results
        final_release="${escaped_release}%0A${escaped_usage}"
        echo "RELEASE_BODY=$final_release" >> $GITHUB_OUTPUT


    - name: Upload builder
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/builder.tar.gz
        asset_name: builder_linux_amd64_deb.tar.gz 
        tag: ${{ github.ref_name }}
        overwrite: true
        prerelease: true
        make_latest: true
        body: ${{ steps.read_release.outputs.RELEASE_BODY }}
    - name: Upload keyringer
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/builder/assets/keyringer
        asset_name: keyringer
        tag: ${{ github.ref_name }}
        overwrite: true
        prerelease: true
        make_latest: true
        body: ${{ steps.read_release.outputs.RELEASE_BODY }}
    - name: Build iso
      run: |
        make build
        gzip -c out/live/live-image-amd64.hybrid.iso > out/live-image-amd64.hybrid.iso.gz
    - name: Upload build
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/live-image-amd64.hybrid.iso.gz
        asset_name: live-image-amd64.hybrid.iso.gz
        tag: ${{ github.ref_name }}
        overwrite: true
        prerelease: true
        make_latest: true
        body: ${{ steps.read_release.outputs.RELEASE_BODY }}
